#!/bin/sh

SITE_PATH="/home/posmac/athoscr/www"

if [ -d public ]
then
  echo 'Clean up'
  rm -rfI public
fi

echo 'Compiling new content'
hugo

echo 'Pushing changes...'
rsync -avz --delete --exclude=papers --exclude=files public/ usp:$SITE_PATH

echo "done."
